---
- name: Installing Packages on Centos
  hosts: all
  become: yes
  tasks:
    - name: Installing packages
      ansible.builtin.yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - wget
        - zip
        - unzip
        - git
        - chrony

    - name: Installing packages on Ubuntu
      ansible.builtin.apt:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - wget
        - zip
        - unzip
        - git
        - chrony

    - name: start the CHRONYD service on Centos 
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: start the CHRONYD service on Ubuntu
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"      
  
    - name: Create a DevOps Group
      ansible.builtin.group:
        name: devops
        state: present

    - name: add users
      ansible.builtin.user:
        name: "{{item}}"
        state: present
        group: devops
      loop: "{{username}}"
    
    - name: Banner file /etc/motd
      copy:
        content: "This {{ansible_distribution}} is managed by ansible. \n"
        dest: /etc/motd    

    - name: Deploy ntp conf on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
      notify: Restart the CHRONYD service on Centos

    - name: Deploy ntp cong on ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/chrony/chrony.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
      notify: Restart the CHRONYD service on Ubuntu

# after made changes in configuration we need to restart the service


  handlers:
    - name: Restart the CHRONYD service on Centos
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Restart the CHRONYD service on Ubuntu
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"


