---
- name: setup db server
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install MySQL
      yum:
        name: mariadb-server
        state: latest
    - name: Start & Enable the MySQL service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Install python 
      yum:
        name: python3-PyMySQL
        state: present
    - name: create new database with name "accounts"
      mysql_db:
        name: accounts
        state: present
    - name: Create database user name "admin"
      mysql_user:
        name: admin
        password: 12345
        priv: '*.*:ALL,GRANT'
        state: present
